# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed1d9291fdf3f999433b2647a65775c77c57375d379cec6831359b1122c072cf72d8122052485bfecd0e49c2a0fbd0e427edf35dffa8b67508b780a5fc375fac
  recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %>
  recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %>

test:
  secret_key_base: 9289bf67eedceb79dff7f12b216c1ff06415d23c28e0188d87f2ece9a196e2c48264e202702ba7e6ab2b13a2bbcec6e8bd45ade425016cb5542fa528764038ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_public_key: <%= ENV["RECAPTCHA_PUBLIC_KEY"] %>
  recaptcha_private_key: <%= ENV["RECAPTCHA_PRIVATE_KEY"] %>
